
services:
  redpanda:
    image: redpandadata/redpanda:v25.3.9
    command:
      - redpanda
      - start
      - --smp=1
      - --reserve-memory=0M
      - --overprovisioned
      - --node-id=1
      - --kafka-addr=PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr=PLAINTEXT://redpanda:29092,OUTSIDE://localhost:9092
    ports:
      - "9092:9092"
      - "29092:29092"
    healthcheck:
      test: ["CMD-SHELL", "rpk cluster info --brokers localhost:29092 || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5
    
  postgres:
    image: postgres:17
    restart: on-failure
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
    ports:
      - "${POSTGRES_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    
  jobmanager:
    container_name: jobmanager
    restart: on-failure
    build:
      context: flink
      dockerfile: Dockerfile.flink
    image: pyflink-crypto
    command: jobmanager
    expose:
      - "6123"
    ports:
      - "8081:8081"
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./flink:/opt/flink/usrlib
      - ./flink/src:/opt/src
      - ./start_jobs.sh:/start_jobs.sh
    depends_on:
      postgres:
        condition: service_healthy
      redpanda:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8081/overview || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  taskmanager:
    container_name: taskmanager
    image: pyflink-crypto
    pull_policy: never
    expose:
      - "6121"
      - "6122"
    init: true
    depends_on:
      jobmanager:
        condition: service_healthy
    command: taskmanager --taskmanager.registration.timeout 5 min
    volumes:
      - ./flink:/opt/flink/usrlib
      - ./flink/src:/opt/src
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.memory.process.size: 1728m
        taskmanager.numberOfTaskSlots: 15
        parallelism.default: 3
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  flink-submit:
    image: pyflink-crypto
    pull_policy: never
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        rest.address: jobmanager
        rest.port: 8081
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      jobmanager:
        condition: service_healthy
    volumes:
      - ./flink/src:/opt/src
    command: >
      bash -c "
      /opt/flink/bin/flink run -py /opt/src/job/ob_aggregate_tumbling_window.py --pyFiles /opt/src -d &
      /opt/flink/bin/flink run -py /opt/src/job/trade_aggregate_tumbling_window.py --pyFiles /opt/src -d &
      wait
      "

  producer:
    build:
      context: producer
      dockerfile: Dockerfile.producer
    container_name: producer
    restart: always
    depends_on:
      redpanda:
        condition: service_healthy
  

